name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '24.3.0'
  PNPM_VERSION: '10.12.4'

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Type check
      run: pnpm compile

    - name: Format check
      run: pnpm format --check

    - name: Build Chrome extension
      run: pnpm build

    - name: Build Firefox extension
      run: pnpm build:firefox

    - name: Create zip files
      run: |
        pnpm zip
        pnpm zip:firefox

    - name: Extract version from tag
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        echo "version=$TAG" >> $GITHUB_OUTPUT

    - name: Upload Chrome build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: ./.output/add-qrcode-generator-icon-back-to-address-bar-chrome-${{ steps.version.outputs.version }}.zip
        retention-days: 30

    - name: Upload Firefox build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: ./.output/add-qrcode-generator-icon-back-to-address-bar-firefox-${{ steps.version.outputs.version }}.zip
        retention-days: 30
